site_name: ProxyStoreBot docs
site_url: https://KONKKA.github.io/diplom_lr/
theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            heading_level: 2
          selection:
            filters:
              - "./app"

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Code: app.md
  - Deployment guide: deployment.md
  - Backup guide: backup.md
  - Update guide: update.md
  - Linting: linting.md

